{{- if .Values.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spotvortex.fullname" . }}-api-key
  labels:
    {{- include "spotvortex.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.apiKey | quote }}
{{- end }}
