apiVersion: v2
name: spotvortex
description: SpotVortex - The Stripe of Spot Computing
type: application
version: 0.0.1
appVersion: "v0.0.1"

keywords:
  - kubernetes
  - spot-instances
  - cost-optimization
  - ml
  - karpenter

home: https://github.com/softcane/spot-vortex-agent
sources:
  - https://github.com/softcane/spot-vortex-agent

maintainers:
  - name: SpotVortex Team
    email: support@spotvortex.io

annotations:
  category: Cost Optimization
